# Docker image is build and pushed for each commit/merge on main branch
# Docker tag only contain git hash and epoch time for any commit/merge on main branch
# When a release is released (pre releases won't trigger) docker tag contains tag name as postfix
# Tag as postfix indicates a production ready docker image and it will be deployed to production
#
# On adverse effect on this approach is that, it creates a new images with same commit hash.
# Risk of having issues is minimum. Better but complex approach would be to query docker registry
# and check for an image with same git hash and create a new docker tag with existing image for production.

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
    - released

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Docker Tag
        id: docker-tag
        if: ${{ github.event_name != 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)" | tee $GITHUB_ENV

      - name: Set Docker Tag - Release
        id: docker-tag-release
        if: ${{ github.event_name == 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)-${GITHUB_REF#refs/tags/}" | tee $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: "false"

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Image Build
        id: docker-build
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: 540854129832.dkr.ecr.us-east-1.amazonaws.com/palm/palm-gnosis-safe-ui:${{ env.DOCKER_TAG }}

      - name: Docker Image Build and Publish
        id: docker-build-publish
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref,'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 540854129832.dkr.ecr.us-east-1.amazonaws.com/palm/palm-gnosis-safe-ui:${{ env.DOCKER_TAG }}
