on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker Tag
        id: docker-tag
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)" | tee $GITHUB_ENV

      - name: Login to Docker Repository
        uses: docker/login-action@v1
        with:
          registry: core-harbor.us-east-2.codefi.network
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_TOKEN }}

      - name: Docker Image Build
        id: docker-build
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: core-harbor.us-east-2.codefi.network/palm/palm-gnosis-safe-ui:${{ env.DOCKER_TAG }}

      - name: Docker Image Build and Publish
        id: docker-build-publish
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: core-harbor.us-east-2.codefi.network/palm/palm-gnosis-safe-ui:${{ env.DOCKER_TAG }}
